### ISSUE TITLE
Desktop 자동 로그인 구현

### ISSUE THREAD

**Issue by gigs4014** [ablecloud-team/ablestack-desktop#10]
#### 이슈 타입

 * 새 기능 아이디어

#### 컴포넌트 이름

~~~
VM
~~~

#### ABLESTACK 버전

~~~
ABLESTACK Bronto
~~~

#### 구성

~~~
- 윈도우 VM에 자동 로그인 기능 구현
~~~

#### OS / 환경

~~~
- 윈도우 : windows 10

~~~

#### 이슈 내용

- [ ] 윈도우 10 자동 로그인 구현

#### 재현 과정

~~~
 
~~~

#### 기대한 결과

~~~

~~~

#### 실제 결과

~~~

~~~

**Comment by SeockMin** [comment]
참고 페이지 
https://libvdi.blogspot.com/2020/09/github.html

위 블로그를 기준으로 작업 진행
