### ISSUE TITLE
Works Admin, User UI - 로그인 화면 개발

### ISSUE THREAD

**Issue by jschoiRR** [ablecloud-team/ablestack-desktop#16]
#### 이슈 타입

 * 새 기능 아이디어

#### 컴포넌트 이름

~~~
UI
~~~

#### ABLESTACK 버전

~~~
Bronto
~~~

#### 구성

~~~

~~~

#### OS / 환경

~~~

~~~

#### 이슈 내용

Works Admin, User UI - 로그인 화면 개발

- [ ] 구성 항목(ID, 비멀번호)
- [ ] 파비콘, 로고, 타이틀, 버전 지정

#### 재현 과정

~~~

~~~

#### 기대한 결과

~~~

~~~

#### 실제 결과

~~~

~~~

**Comment by gigs4014** [comment]
- [ ] 로그인 시 관리자인지 일반 유저인지 확인하는 개발
- [ ] 관리자이면 관리자 페이지만 접속 할 수 있는 기능 개발
- [ ] 일반 유저이면 일반 유저 페이지만 접속 할 수 있는 기능 개발
- [ ] API 서버에서 생성된 토큰을 이용한 페이지 이동시 사용할수 있는 기능 개발
