### ISSUE TITLE
DaaS 외부 접속을 위한 Proxy 서버 설정

### ISSUE THREAD

**Issue by gigs4014** [ablecloud-team/ablestack-desktop#3]
#### 이슈 타입

 * 새 기능 아이디어

#### 컴포넌트 이름

~~~
API
~~~

#### ABLESTACK 버전

~~~
ABLESTACK Bronto
~~~

#### 구성

~~~
- Mold 의 isolated network 환경에서 윈도우 가상머신 2대 생성.
- 동일한 isolated network 에 centos 8 구성 후 proxy 구성
- public ip centos 8 에 연결 후 외부에서 접속 테스트
~~~

#### OS / 환경

~~~
- 윈도우 : windows 10
- proxy server : centos 8
~~~

#### 이슈 내용

- [x] nginx 를 이용한 port forwading 연결 테스트

#### 재현 과정

~~~

~~~

#### 기대한 결과

~~~

~~~

#### 실제 결과

~~~

~~~

**Comment by SeockMin** [comment]
# NGINX 를 이용한 Port forwding 테스트
1. centos 8 에 NGINX 설치
''' bash
dnf install nginx
'''

**Comment by SeockMin** [comment]
# NGINX 재기동 관련된 내용
- 기존의 테스트시 SELinux  Enable 상태에서 테스트 진행하면서 정상적으로 NGINX 가 올라오지 못하여 에러가 발생하여 NGNIX reload 테스트가 정상적으로 진행이 안되였습니다.
- SELinux 와 firewalld 두개 서비스를 정지 후 ```systemctl reload nginx``` 명령어를 이용하여 reload 해보니 정상적으로 설정이 적용 되었습니다. 
- SELinux 에 대해 미리 설정을 해야 할듯 합니다.
