### ISSUE TITLE
한컴 구름 OS  구성

### ISSUE THREAD

**Issue by gigs4014** [ablecloud-team/ablestack-desktop#6]
#### 이슈 타입

 * 새 기능 아이디어

#### 컴포넌트 이름

~~~
가상머신 구성
~~~

#### ABLESTACK 버전

~~~
ABLESTACK Bronto
~~~

#### 구성

~~~
- 한컴 구름 OS 를 Mold 에서 설치 및 구성해보기
~~~

#### OS / 환경

~~~
- OS : 한컴 구름 OS 2.2
~~~

#### 이슈 내용

- [ ] 한컴 구름 OS 2.2 를 Mold 환경에서 설치
- [x] virt-manager 를 이용한 하이퍼 바이저에 직접 설치

#### 재현 과정

~~~

~~~

#### 기대한 결과

~~~

~~~

#### 실제 결과

~~~

~~~

**Comment by SeockMin** [comment]
# 한컴 OS 를 기 구성되여있는 Mold 에 ISO 업로드 후 설치 진행 결과

## ISO 등록 후 Mold 에서 생성결과 정상적으로 부팅이 안되는 현상이 발생

![스크린샷 2021-05-14 오전 10 41 40](https://user-images.githubusercontent.com/5581961/118208214-50026280-b4a1-11eb-92be-773f422a676c.png)

## virt-manager 를 이용하여 생성한 결과 정상적으로 생성됨

![스크린샷 2021-05-14 오전 10 45 54](https://user-images.githubusercontent.com/5581961/118208373-9d7ecf80-b4a1-11eb-8e90-990446248d6d.png)

Mold 상에서 구성이 안된 이유는 조금더 확인 필요
