### ISSUE TITLE
VDI 프레임 테스트

### ISSUE THREAD

**Issue by gigs4014** [ablecloud-team/ablestack-desktop#8]
#### 이슈 타입

 * 새 기능 아이디어

#### 컴포넌트 이름

~~~
VM
~~~

#### ABLESTACK 버전

~~~
ABLESTACK Bronto
~~~

#### 구성

~~~
- CPU : 4core, MEM : 8GB, Disk : 100GiB 기준으로 테스트
- Mold 에서 ISO를 이용한 VM 생성
- Mold 에서 사용한 ISO를 이용하여 virt-manager 에서 VM 생성
- 동일한 유튜브 동영상 재생
- 동일한 동영상 파일 동일한 프로그램을 이용하여 재생
~~~

#### OS / 환경

~~~
- 윈도우 : windows 10

~~~

#### 이슈 내용

- [x] VNC 서버 => Spice 서버 변경 후 Mold Web console 테스트
- [x] VNC 서버, Spice 서버 2개 디스 플레이 등록 후 테스트
- [ ] Mold 에서 생성한  윈도우10 이랑 virt-manager 에서 생성한 윈도우 10 동영상 프레임 test

#### 재현 과정

~~~
 
~~~

#### 기대한 결과

~~~

~~~

#### 실제 결과

~~~

~~~

**Comment by SeockMin** [comment]
# Mold 에서 생성한 Guest VM에 디스플레이 type 을 VNC -> Spice 로 변경 테스트
테스트 결과 virt-manager 에서는 정상적으로 콘솔이 보이나 Mold 의 no-vnc에서는 정상적으로  화면이 보이지 않았습니다.

# virt-manager 를 이용한 Spice 서버 등록 (VNC, Spice 총 2개의 디스플레이등록)
테스트 결과 virt-manager 에서 2개의 디스플레이 pci는 정상적으로 등록되고 부팅도 정상적으로 되었으나
Mold 의 web console (no-vnc)에서는 화면이 정상적으로 보이지 않았습니다.

**Comment by SeockMin** [comment]
# virt-manager 를 이용한 Spice 서버 등록 (VNC, Spice 총 2개의 디스플레이등록)
테스트 결과 virt-manager 에서 2개의 디스플레이 pci는 정상적으로 등록되고 부팅도 정상적으로 되었으나
Mold 의 web console (no-vnc)에서는 화면이 정상적으로 보이지 않았습니다.

![스크린샷 2021-05-17 오후 2 16 26](https://user-images.githubusercontent.com/5581961/118435761-8565b500-b71a-11eb-8b27-c0c469ba1013.png)

**Comment by jschoiRR** [comment]
* 유튜브 실행테스트 1080p(Win10 4C-8G)

=> 테스트 영상 확인
https://172.16.0.254:5001/d/f/622090061164361329

**Comment by jschoiRR** [comment]
* 동영상 파일 실행 테스트 
  1920×1080 | MP4 | 32.1 MB

* Win10 4C-8G
 
=> 테스트 영상 확인

**Comment by jschoiRR** [comment]
* spice 드라이버 설치

<img width="762" alt="스크린샷 2021-05-31 오전 12 17 13" src="https://user-images.githubusercontent.com/77760789/120109756-cee7e280-c1a5-11eb-9050-7bb3fde9d257.png">

**Comment by jschoiRR** [comment]
* RDP remoteFX 활성화 관련 참고 
https://rosagigantea.tistory.com/652
https://m.blog.naver.com/qhagosk0277/221957885625

**Comment by jschoiRR** [comment]
* 테스트 결과 확인
 1. spice 서버로 접속 :
    -  win10 가상머신에 spice 드라이브를 설치하지 않을 시 정상적으로 렌더링이 되지 않아 조작하기 어려울 정도.
    - 드라이브 설치 후 video type이 QXL(ram: 128 max)일 경우만 정상적인 조작 가능
   
 2. RDP 접속 
   - spice 드라이버 설치 전과 후 비교 시 시각적으로 크게 변화없음. 
   - remoteFX 활성화 설정 후 크게 렌더링의 차이를 보이지 않음.
   - video type은 cirrus, QXL, VGA 테스트

**Comment by jschoiRR** [comment]
test6 - RDP 접속(10.10.10.150) : spice 드라이버 설치 + QXL + RAM 256m + remoteFX 활성화
